apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kubectl
      image: internal-registry.tkg.mobilink.net.pk/wso2-dev/jenkins-kubectl
      command:
        - /bin/cat
      tty: true
    - name: kaniko
      image: internal-registry.tkg.mobilink.net.pk/wso2-dev/kaniko-executor:v1.0
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
